// create person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Aoba Suzukaze",
    "number": "75-8309681"
}

###
// create person without name and number
POST http://localhost:3001/api/persons
Content-Type: application/json

###
// create person without name
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "75-7443951"
}

###
// create person without number
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Nene Sakura"
}

###
// create person with name length of less than 3 characters
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Ai",
    "number": "75-8693202"
}

###
// create person with a phone number length less than 8
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Sakura Nene",
    "number": "75-1651"
}

###
// create person with invalid phone number format
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Sakura Nene",
    "number": "7-51651653"
}
###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Sakura Nene",
    "number": "75-16-516531"
}
###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Sakura Nene",
    "number": "75 165 1653"
}