// create person
POST https://spring-meadow-6832.fly.dev/api/persons/
Content-Type: application/json

{
    "name": "Aoba Suzukaze",
    "number": "75 830 9681"
}

###
// create person without name and number
POST https://spring-meadow-6832.fly.dev/api/persons/
Content-Type: application/json

###
// create person without name
POST https://spring-meadow-6832.fly.dev/api/persons/
Content-Type: application/json

{
    "number": "75 744 3951"
}

###
// create person without number
POST https://spring-meadow-6832.fly.dev/api/persons/
Content-Type: application/json

{
    "name": "Nene Sakura"
}

###
// create person with name length of less than 3 characters
POST https://spring-meadow-6832.fly.dev/api/persons
Content-Type: application/json

{
    "name": "Ai",
    "number": "75 869 3202"
}