PUT https://spring-meadow-6832.fly.dev/api/persons/649485be2b1739400d2b0ac9
Content-Type: application/json

{
    "name": "Aoba Suzukaze",
    "number": "75-7443951"
}

###
// update person with a name less than 3 characters
PUT https://spring-meadow-6832.fly.dev/api/persons/649485be2b1739400d2b0ac9
Content-Type: application/json

{
    "name": "Ai",
    "number": "75-4154816"
}

###
// update person with a phone number length less than 8
PUT https://spring-meadow-6832.fly.dev/api/persons/649485be2b1739400d2b0ac9
Content-Type: application/json

{
    "name": "Aoba Suzukaze",
    "number": "75-1651"
}

###
// update person with invalid phone number format
PUT https://spring-meadow-6832.fly.dev/api/persons/649485be2b1739400d2b0ac9
Content-Type: application/json

{
    "name": "Aoba Suzukaze",
    "number": "7-51651653"
}
###
PUT https://spring-meadow-6832.fly.dev/api/persons/649485be2b1739400d2b0ac9
Content-Type: application/json

{
    "name": "Aoba Suzukaze",
    "number": "75-16-516531"
}
###
PUT https://spring-meadow-6832.fly.dev/api/persons/649485be2b1739400d2b0ac9
Content-Type: application/json

{
    "name": "Aoba Suzukaze",
    "number": "75 165 1653"
}